root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "tmp/api"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata", "docs"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  stop_on_error = true
  send_interrupt = true
  kill_delay = 2000

[log]
  time = true

[misc]
  clean_on_exit = true